FROM node:10.16.3-alpine AS build_env

MAINTAINER dudulu <solacowa@gmail.com>

RUN npm config set registry https://registry.npm.taobao.org

RUN npm install -g gitbook-cli github highlight search mygitalk copy-code-button code expandable-chapters back-to-top-button sharing-plus
RUN mkdir -p /opt/data
COPY ./README.md /opt/data
WORKDIR /opt/data
RUN gitbook fetch 3.2.3
RUN gitbook build

CMD ["bash"]
