FROM docker-prod-virtual.repo.yrd.creditease.corp/gitbook:v3.2.3 AS build_env

COPY ./ /opt/gitbook

WORKDIR /opt/gitbook

RUN gitbook build

FROM nginx:1.17.3-alpine

COPY --from=build_env /opt/gitbook/_book/ /usr/share/nginx/html/

CMD ["nginx", "-g", "daemon off;"]
